Added JUnit report to action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,6 +41,14 @@ jobs:
       - name: Run tests
         run: make test
 
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JUnit Report
+          path: build/test-results/test/*.xml
+          reporter: java-junit
+
       - name: Lint code (Checkstyle)
         run: make lint
 
